services:
  mapme-expo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # for mac users
    #platform: linux/amd64
    ports:
      - 8081:8081
    env_file: ".env"
    networks:
      - mapme-network
    volumes:
      - /app/node_modules
networks:
  mapme-network:
    driver: bridge