services:
  mapme-db:
    image: postgis/postgis:16-3.5
    restart: unless-stopped
    ports:
      - 5432:5432
    #for mac users 
    #platform: linux/amd64
    env_file: ".env"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - music_map_pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - mapme-network
volumes:
  music_map_pgdata:

networks:
  mapme-network:
    driver: bridge
